name: Platform CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (download project)
        uses: actions/checkout@v3

      - name: Setup Python (install Python on cloud computer)
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Print message to check pipeline
        run: echo "Pipeline running successfully! ðŸš€"

      - name: Check SQL file exists
        run: |
          if [ -f "data.sql" ]; then
            echo "SQL file exists! ðŸŸ¢"
          else
            echo "SQL file missing! ðŸ”´"
            exit 1
          fi

      - name: Build Docker Image
        run: docker build -t my-data-platform -f docker/dockerfile .

      - name: Run Docker Container
        run: docker run my-data-platform
